source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ‘8.0’
use_frameworks!

target ‘PXTutorialSample’ do
    pod 'PXTutorial', :git =>'https://github.com/MalekEBelkahla/PXTutorial.git'
end
